import configparser

config = configparser.ConfigParser()
config.read("config.ini")

MONGO_DB_NAME = config["DATABASE"]["MONGO_DB_NAME"]
MONGO_URL = config["DATABASE"]["MONGO_URL"]
MONGO_USER = config["DATABASE"]["MONGO_USER"]
MONGO_PASSWORD = config["DATABASE"]["MONGO_PASSWORD"]
MAX_CONNECTIONS_COUNT = config["DATABASE"]["MAX_CONNECTIONS_COUNT"]
MIN_CONNECTIONS_COUNT = config["DATABASE"]["MIN_CONNECTIONS_COUNT"]
MONGO_URI = f"mongodb://{MONGO_USER}:{MONGO_PASSWORD}@{MONGO_URL}/{MONGO_DB_NAME}?maxPoolSize={MAX_CONNECTIONS_COUNT}&minPoolSize={MIN_CONNECTIONS_COUNT}"


AZURE_CHATBOT_API_KEY = config["AZURE_CHATBOT"]["AZURE_CHATBOT_API_KEY"]
AZURE_CHATBOT_ENDPOINT = config["AZURE_CHATBOT"]["AZURE_CHATBOT_ENDPOINT"]
AZURE_CHATBOT_OPENAI_VERSION = config["AZURE_CHATBOT"]["AZURE_CHATBOT_OPENAI_VERSION"]

SECRET_KEY = config["ENCRYPTION"]["SECRET_KEY"]
ALGORITHM = config["ENCRYPTION"]["ALGORITHM"]
